name: PR

on: [pull_request,release]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.17.1"
      - run: flutter pub get
      - run: flutter analyze lib example/lib
      # - run: flutter test
      - run: cd example ; flutter build apk --debug
      - run: cd example ; flutter build ios --no-codesign
